version: "3"

services: 
  api:
    build:
      context: .
      dockerfile: operations/docker/Dockerfile.dev
    ports: 
      - "3000:3000"
    environment: 
      - PORT=8080
    volumes: 
      - ".:/go/src/github.com/badmuts/go-todo-rest"

  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_USER=api
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=test
